spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"