spring:
  data:
    mongodb:
      authentication-database: admin
      username: ${mongodb.username}
      password: ${mongodb.password}
      database: fail_db
      port: 27018
      host: localhost
    redis:
      host: localhost
      port: 6379
      password: ${redis.cache.password}
  cache:
    type: redis
management:
  endpoints:
    web:
      exposure:
        include: "*"
